version: '3.8'

services:
  keycloak_db:
    image: postgres:14
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - ./postgres-keycloak-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
      KC_HOSTNAME_DEBUG: "true"
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    depends_on:
      - keycloak_db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  reports-api:
    build:
      context: ./reports-api
      dockerfile: Dockerfile
    ports:
      - "8001:8001"

  bionicpro-auth:
    build:
      context: ./bionicpro-auth
      dockerfile: Dockerfile
    environment:
      FRONTEND_URL: http://localhost:3000
      REPORTS_API_URL: http://reports-api:8001
      KEYCLOAK_INTERNAL_BASE_URL: http://host.docker.internal:8080
      KEYCLOAK_PUBLIC_BASE_URL: http://localhost:8080
      KEYCLOAK_REALM: reports-realm
      KEYCLOAK_CLIENT_ID: bionicpro-auth
      KEYCLOAK_CLIENT_SECRET: super-secret-auth-client
      SESSION_COOKIE_NAME: bp_session
      SESSION_COOKIE_SECURE: "false"
      SESSION_COOKIE_HTTPONLY: "true"
      SESSION_COOKIE_SAMESITE: lax
      SESSION_TTL_SECONDS: "1800"
      REDIS_URL: redis://redis:6379/0
      REFRESH_TOKEN_ENCRYPTION_KEY: 0123456789abcdef0123456789abcdef
      ROTATE_SESSION_EVERY_REQUEST: "true"
      REFRESH_ACCESS_TOKEN_SKEW_SECONDS: "15"
    ports:
      - "8000:8000"
    depends_on:
      - keycloak
      - redis
      - reports-api

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - bionicpro-auth
