services:
  ldap:
    build:
      context: ./ldap
      dockerfile: Dockerfile
    environment:
      LDAP_ORGANISATION: BionicPRO Foreign Office
      LDAP_DOMAIN: example.com
      LDAP_ADMIN_PASSWORD: admin
      LDAP_CONFIG_PASSWORD: config
      LDAP_TLS: "false"
    ports:
      - "389:389"
    healthcheck:
      test: ["CMD-SHELL", "ldapsearch -x -H ldap://localhost:389 -D 'cn=admin,dc=example,dc=com' -w admin -b 'dc=example,dc=com' '(objectClass=*)' >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 10

  keycloak_db:
    image: postgres:14
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - ./postgres-keycloak-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak_user -d keycloak_db" ]
      interval: 5s
      timeout: 5s
      retries: 20

  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
      KC_HOSTNAME_DEBUG: "true"
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    depends_on:
      keycloak_db:
        condition: service_healthy
      ldap:
        condition: service_healthy

  keycloak-ldap-init:
    image: quay.io/keycloak/keycloak:21.1
    depends_on:
      keycloak:
        condition: service_started
      ldap:
        condition: service_healthy
    volumes:
      - ./keycloak/configure-ldap.sh:/opt/keycloak/configure-ldap.sh
    entrypoint: ["/bin/sh", "/opt/keycloak/configure-ldap.sh"]

  keycloak-mfa-init:
    image: quay.io/keycloak/keycloak:21.1
    depends_on:
      keycloak:
        condition: service_started
      keycloak-ldap-init:
        condition: service_completed_successfully
    volumes:
      - ./keycloak/configure-mfa.sh:/opt/keycloak/configure-mfa.sh
    entrypoint: [ "/bin/sh", "/opt/keycloak/configure-mfa.sh" ]

  keycloak-yandex-init:
    image: quay.io/keycloak/keycloak:21.1
    depends_on:
      keycloak:
        condition: service_started
      keycloak-ldap-init:
        condition: service_completed_successfully
      keycloak-mfa-init:
        condition: service_completed_successfully
    environment:
      KEYCLOAK_BASE_URL: http://keycloak:8080
      KEYCLOAK_REALM: reports-realm
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      YANDEX_IDP_ALIAS: yandex
      YANDEX_CLIENT_ID: ${YANDEX_CLIENT_ID}
      YANDEX_CLIENT_SECRET: ${YANDEX_CLIENT_SECRET}
      YANDEX_OIDC_ISSUER: ${YANDEX_OIDC_ISSUER}
      YANDEX_OIDC_AUTH_URL: ${YANDEX_OIDC_AUTH_URL}
      YANDEX_OIDC_TOKEN_URL: ${YANDEX_OIDC_TOKEN_URL}
      YANDEX_OIDC_USERINFO_URL: ${YANDEX_OIDC_USERINFO_URL}
      YANDEX_OIDC_JWKS_URL: ${YANDEX_OIDC_JWKS_URL}
    volumes:
      - ./keycloak/configure-yandex-id.sh:/opt/keycloak/configure-yandex-id.sh
    entrypoint: [ "/bin/sh", "/opt/keycloak/configure-yandex-id.sh" ]

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  crm_db:
    image: postgres:14
    environment:
      POSTGRES_DB: crm_db
      POSTGRES_USER: crm_user
      POSTGRES_PASSWORD: crm_password
    volumes:
      - crm-data:/var/lib/postgresql/data
      - ./postgres-crm/init:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crm_user -d crm_db"]
      interval: 5s
      timeout: 5s
      retries: 20

  oltp_db:
    image: postgres:14
    environment:
      POSTGRES_DB: oltp_db
      POSTGRES_USER: oltp_user
      POSTGRES_PASSWORD: oltp_password
    volumes:
      - oltp-data:/var/lib/postgresql/data
      - ./postgres-oltp/init:/docker-entrypoint-initdb.d
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oltp_user -d oltp_db"]
      interval: 5s
      timeout: 5s
      retries: 20

  data-generator:
    build:
      context: ./scripts
      dockerfile: Dockerfile
    environment:
      CRM_DATABASE_URL: postgresql://crm_user:crm_password@crm_db:5432/crm_db
      OLTP_DATABASE_URL: postgresql://oltp_user:oltp_password@oltp_db:5432/oltp_db
    depends_on:
      crm_db:
        condition: service_healthy
      oltp_db:
        condition: service_healthy

  clickhouse:
    image: clickhouse/clickhouse-server:24.3
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./clickhouse/init:/docker-entrypoint-initdb.d
      - ./clickhouse/config/users.xml:/etc/clickhouse-server/users.d/default-password.xml
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --query 'SELECT 1'"]
      interval: 5s
      timeout: 5s
      retries: 20

  airflow:
    image: apache/airflow:2.10.4-python3.11
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      AIRFLOW__CORE__FERNET_KEY: ""
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      _PIP_ADDITIONAL_REQUIREMENTS: "clickhouse-connect==0.8.14 apache-airflow-providers-postgres==5.13.1 apache-airflow-providers-http==4.13.2"
      AIRFLOW_CONN_CRM_POSTGRES: postgresql://crm_user:crm_password@crm_db:5432/crm_db
      AIRFLOW_CONN_OLTP_POSTGRES: postgresql://oltp_user:oltp_password@oltp_db:5432/oltp_db
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    ports:
      - "8082:8080"
    command: >
      bash -c "
        airflow db init &&
        airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com &&
        airflow webserver --port 8080 &
        airflow scheduler
      "
    depends_on:
      clickhouse:
        condition: service_healthy
      crm_db:
        condition: service_healthy
      oltp_db:
        condition: service_healthy

  reports-api:
    build:
      context: ./reports-api
      dockerfile: Dockerfile
    environment:
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: "8123"
    ports:
      - "8001:8001"
    depends_on:
      clickhouse:
        condition: service_healthy

  bionicpro-auth:
    build:
      context: ./bionicpro-auth
      dockerfile: Dockerfile
    environment:
      FRONTEND_URL: http://localhost:3000
      REPORTS_API_URL: http://reports-api:8001
      KEYCLOAK_INTERNAL_BASE_URL: http://host.docker.internal:8080
      KEYCLOAK_PUBLIC_BASE_URL: http://localhost:8080
      KEYCLOAK_REALM: reports-realm
      KEYCLOAK_CLIENT_ID: bionicpro-auth
      KEYCLOAK_CLIENT_SECRET: super-secret-auth-client
      SESSION_COOKIE_NAME: bp_session
      SESSION_COOKIE_SECURE: "false"
      SESSION_COOKIE_HTTPONLY: "true"
      SESSION_COOKIE_SAMESITE: lax
      SESSION_TTL_SECONDS: "1800"
      REDIS_URL: redis://redis:6379/0
      REFRESH_TOKEN_ENCRYPTION_KEY: 0123456789abcdef0123456789abcdef
      ROTATE_SESSION_EVERY_REQUEST: "true"
      REFRESH_ACCESS_TOKEN_SKEW_SECONDS: "15"
      DATABASE_URL: postgresql+psycopg2://keycloak_user:keycloak_password@keycloak_db:5432/keycloak_db
      DATABASE_SCHEMA: bionicpro_auth
    ports:
      - "8000:8000"
    depends_on:
      - keycloak
      - redis
      - reports-api

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - bionicpro-auth

volumes:
  clickhouse-data:
  crm-data:
  oltp-data:
